name: release

on:
  push:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        package: ["test_validation"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools setuptools_scm wheel

      - name: Build packages
        run: python setup.py sdist bdist_wheel

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/test_validation
      
    steps:
      - name: download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
        
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          skip-existing: true
          verbose: true
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          
