name: release 

on:
  push:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        package: ["test_validation"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools setuptools_scm wheel

      - name: Build packages
        run: python setup.py sdist bdist_wheel
        
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          packages_dir: dist/
          skip-existing: true
          verbose: true
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          
